language: python
os:
  - linux
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install tox-travis
  - pip install codecov
  - pip install grg-mpdata grg-grgdata # required for calling check_version
script:
  - tox
  - ./check_version.py
after_success:
  - codecov
